import { Poppins } from 'next/font/google'
import './globals.css'

const poppins = Poppins({ subsets: ['latin'], weight: ["500",  "600", "700"] })

export const metadata = {
  title: 'Typing test game',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className}  container mx-auto bg-primary`}>{children}</body>
    </html>
  )
}
